[package]
name = "Rex"
version = "3.0.1"
edition = "2024"

[dependencies]
recursive_copy = "1.2"
tar_minimal = "1.1"
zstd = { version = "0.13", default-features = false }
rldd_minimal = "1.1"

[profile.release]
opt-level = "z"
panic = "abort"
codegen-units = 1
lto = true
strip = true
debug = false
overflow-checks = false
split-debuginfo = "off"
